# Generated by Django 5.1.5 on 2025-01-15 11:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("blocked", "Blocked"),
                            ("stopped", "Stopped"),
                        ],
                        default="stopped",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VPS",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cpu", models.PositiveIntegerField(verbose_name="CPU")),
                ("ram", models.PositiveIntegerField(verbose_name="RAM")),
                ("hdd", models.PositiveIntegerField(verbose_name="HDD")),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.status",
                        verbose_name="Статус",
                    ),
                ),
            ],
        ),
    ]
