# Generated by Django 5.1.5 on 2025-01-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vps",
            name="status",
            field=models.CharField(
                choices=[
                    ("started", "Started"),
                    ("blocked", "Blocked"),
                    ("stopped", "Stopped"),
                ],
                default="stopped",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="vps",
            name="cpu",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="vps",
            name="hdd",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="vps",
            name="ram",
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name="Status",
        ),
    ]
